{
 "title": "Container State Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Running Containers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"default\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting Containers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"default\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Terminated Containers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"default\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAX_CPU_USAGE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (\r\n  rate(container_cpu_usage_seconds_total{namespace=\"default\", container!=\"\", container!=\"POD\"}[5m]) \r\n  * 100\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAX_MEMORY_USAGE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (\r\n  container_memory_usage_bytes{namespace=\"default\", container!=\"\", container!=\"POD\"} / 1024 / 1024\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization of Individual Pods",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", container!=\"\", container!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\", container!=\"\", container!=\"POD\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}