apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-health-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  groups:
  - name: pod-health-alerts
    rules:
    - alert: PodUnhealthy
      expr: kube_pod_status_ready{condition="true"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is Unhealthy"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not ready for more than 2 minutes."
    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[5m]) > 0.5
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is CrashLooping"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been restarting frequently."
    - alert: PodNotRunning
      expr: kube_pod_status_phase{phase="Running"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is Not Running"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not in Running state."
    - alert: PodNotScheduled
      expr: kube_pod_status_phase{phase="Pending"} > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is Not Scheduled"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not scheduled."
    - alert: PodNotReady
      expr: kube_pod_status_ready{condition="true"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is Not Ready"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not ready."
    - alert: PodImagePullBackOff
    
      expr: kube_pod_container_status_waiting_reason{reason="ImagePullBackOff"} > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is in ImagePullBackOff state"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in ImagePullBackOff state."
    - alert: PodImagePullError
      
      expr: kube_pod_container_status_waiting_reason{reason="ErrImagePull"} > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is in ErrImagePull state"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in ErrImagePull state."
    
    - alert: PodTerminated
      expr: kube_pod_status_phase{phase=~"Failed|Unknown"} > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is Terminated or in Unknown state"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has moved to {{ $labels.phase }} phase."
