
grafana:
  adminPassword: admin  # Change this to a secure password
  # dashboardsConfigMaps:
  #   default: "grafana-dashboard-config"
  # dashboardProviders:
  #   dashboardproviders.yaml:
  #     apiVersion: 1
  #     providers:
  #       - name: 'default'
  #         orgId: 1
  #         folder: ''
  #         type: file
  #         disableDeletion: false
  #         editable: true
  #         options:
  #           path: ./dashboard.json
global:
  resolve_timeout: 5m

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 30s
      repeat_interval: 1h
      receiver: 'slack-notifications'
      routes:
      - match:
          severity: critical
        receiver: 'slack-notifications'
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#alerts'
        api_url: 'your-slack-webhook-url'
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        icon_emoji: ':warning:'

prometheus:
  prometheusSpec:
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
